// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCiav1MZWwPwJBLOjUh9tAJfRFNIOYdCFs',
    appId: '1:249836205814:web:af3eb48bc6353214e6ded7',
    messagingSenderId: '249836205814',
    projectId: 'tripapp-iramdev-cb07a',
    authDomain: 'tripapp-iramdev-cb07a.firebaseapp.com',
    storageBucket: 'tripapp-iramdev-cb07a.firebasestorage.app',
    measurementId: 'G-7Q1SNV4J2C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-BCEF2bSLenb2hmxxDXOR8vEGuWfj_fg',
    appId: '1:249836205814:android:4b0f9d871e142ff1e6ded7',
    messagingSenderId: '249836205814',
    projectId: 'tripapp-iramdev-cb07a',
    storageBucket: 'tripapp-iramdev-cb07a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDK94uHUuTOHpjv2wQY9st95SbH6sPOuV8',
    appId: '1:249836205814:ios:9eb5166fdfac8606e6ded7',
    messagingSenderId: '249836205814',
    projectId: 'tripapp-iramdev-cb07a',
    storageBucket: 'tripapp-iramdev-cb07a.firebasestorage.app',
    iosBundleId: 'com.example.tripApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDK94uHUuTOHpjv2wQY9st95SbH6sPOuV8',
    appId: '1:249836205814:ios:9eb5166fdfac8606e6ded7',
    messagingSenderId: '249836205814',
    projectId: 'tripapp-iramdev-cb07a',
    storageBucket: 'tripapp-iramdev-cb07a.firebasestorage.app',
    iosBundleId: 'com.example.tripApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCiav1MZWwPwJBLOjUh9tAJfRFNIOYdCFs',
    appId: '1:249836205814:web:0d02b5fa3f0f9218e6ded7',
    messagingSenderId: '249836205814',
    projectId: 'tripapp-iramdev-cb07a',
    authDomain: 'tripapp-iramdev-cb07a.firebaseapp.com',
    storageBucket: 'tripapp-iramdev-cb07a.firebasestorage.app',
    measurementId: 'G-GRPQVFL18T',
  );

}